### ISSUE TITLE
留个联系方式呗，感兴趣想合作

### ISSUE THREAD

**Issue by willwill85** [mywang44/snoring_net#1]

**Comment by mywang44** [comment]
您好，本项目属于科大讯飞聆思科技的开源demo，如果您想了解更多信息，可以关注聆思科技公众号，加入开发者交流群
https://mp.weixin.qq.com/s/nykdqNJ29YEIjJ6JVeg8ng

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: will ***@***.***&gt;
发送时间: 2024年1月19日 18:02
收件人: mywang44/snoring_net ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [mywang44/snoring_net] 留个联系方式呗，感兴趣想合作 (Issue #1)





 
Closed #1 as completed.
